INSERT INTO Dim_Customers (CustomerID, CustomerName, City, Country, Segment) VALUES
(1, 'Ahmet Çelik', 'Bursa', 'Türkiye', 'Bireysel'),
(2, 'Burak Kaya', 'Ankara', 'Türkiye', 'Bireysel'),
(3, 'Ahmet Yılmaz', 'Ankara', 'Türkiye', 'Bireysel'),
(4, 'Hasan Doğan', 'İstanbul', 'Türkiye', 'Bireysel'),
(5, 'Burak Arslan', 'Adana', 'Türkiye', 'Bireysel'),
(6, 'Hüseyin Çelik', 'İstanbul', 'Türkiye', 'Bireysel'),
(7, 'TR Lojistik A.Ş.', 'Adana', 'Türkiye', 'Kurumsal'),
(8, 'Ayşe Şahin', 'Konya', 'Türkiye', 'Bireysel'),
(9, 'Zeynep Kaya', 'Konya', 'Türkiye', 'Bireysel'),
(10, 'TR Holding A.Ş.', 'Antalya', 'Türkiye', 'Kurumsal'),
(11, 'TR Yazılım A.Ş.', 'Ankara', 'Türkiye', 'Kurumsal'),
(12, 'TR Yazılım A.Ş.', 'Ankara', 'Türkiye', 'Kurumsal'),
(13, 'Can Doğan', 'Konya', 'Türkiye', 'Bireysel'),
(14, 'Burak Kaya', 'İstanbul', 'Türkiye', 'Bireysel'),
(15, 'TR Ticaret A.Ş.', 'Ankara', 'Türkiye', 'Kurumsal'),
(16, 'TR Teknoloji A.Ş.', 'Adana', 'Türkiye', 'Kurumsal'),
(17, 'Merve Yıldız', 'İzmir', 'Türkiye', 'Bireysel'),
(18, 'Fatma Çelik', 'Ankara', 'Türkiye', 'Bireysel'),
(19, 'Ayşe Arslan', 'Bursa', 'Türkiye', 'Bireysel'),
(20, 'Zeynep Çelik', 'Bursa', 'Türkiye', 'Bireysel'),
(21, 'TR Teknoloji A.Ş.', 'Bursa', 'Türkiye', 'Kurumsal'),
(22, 'TR Ticaret A.Ş.', 'Adana', 'Türkiye', 'Kurumsal'),
(23, 'Fatma Doğan', 'Konya', 'Türkiye', 'Bireysel'),
(24, 'Emine Öztürk', 'Gaziantep', 'Türkiye', 'Bireysel'),
(25, 'Ayşe Şahin', 'Antalya', 'Türkiye', 'Bireysel'),
(26, 'TR Yazılım A.Ş.', 'Adana', 'Türkiye', 'Kurumsal'),
(27, 'Ayşe Arslan', 'Gaziantep', 'Türkiye', 'Bireysel'),
(28, 'Ahmet Kaya', 'İzmir', 'Türkiye', 'Bireysel'),
(29, 'Elif Öztürk', 'Ankara', 'Türkiye', 'Bireysel'),
(30, 'Hüseyin Aydın', 'Antalya', 'Türkiye', 'Bireysel'),
(31, 'TR Teknoloji A.Ş.', 'Ankara', 'Türkiye', 'Kurumsal'),
(32, 'TR Holding A.Ş.', 'Antalya', 'Türkiye', 'Kurumsal'),
(33, 'TR Ticaret A.Ş.', 'Ankara', 'Türkiye', 'Kurumsal'),
(34, 'Ayşe Aydın', 'İstanbul', 'Türkiye', 'Bireysel'),
(35, 'TR Ticaret A.Ş.', 'İzmir', 'Türkiye', 'Kurumsal'),
(36, 'Mehmet Çelik', 'Bursa', 'Türkiye', 'Bireysel'),
(37, 'Elif Demir', 'İstanbul', 'Türkiye', 'Bireysel'),
(38, 'Emine Yılmaz', 'Ankara', 'Türkiye', 'Bireysel'),
(39, 'TR Ticaret A.Ş.', 'Bursa', 'Türkiye', 'Kurumsal'),
(40, 'Ece Doğan', 'Ankara', 'Türkiye', 'Bireysel'),
(41, 'Emine Kaya', 'İzmir', 'Türkiye', 'Bireysel'),
(42, 'Emine Arslan', 'İzmir', 'Türkiye', 'Bireysel'),
(43, 'Can Doğan', 'Adana', 'Türkiye', 'Bireysel'),
(44, 'TR Holding A.Ş.', 'Bursa', 'Türkiye', 'Kurumsal'),
(45, 'TR Yazılım A.Ş.', 'Konya', 'Türkiye', 'Kurumsal'),
(46, 'Hasan Aydın', 'Ankara', 'Türkiye', 'Bireysel'),
(47, 'Mehmet Yıldız', 'İstanbul', 'Türkiye', 'Bireysel'),
(48, 'Fatma Doğan', 'Bursa', 'Türkiye', 'Bireysel'),
(49, 'Burak Yılmaz', 'Bursa', 'Türkiye', 'Bireysel'),
(50, 'Ahmet Yıldız', 'Ankara', 'Türkiye', 'Bireysel'),
(51, 'Mustafa Aydın', 'Bursa', 'Türkiye', 'Bireysel'),
(52, 'Burak Doğan', 'Gaziantep', 'Türkiye', 'Bireysel'),
(53, 'Emine Öztürk', 'Bursa', 'Türkiye', 'Bireysel'),
(54, 'Merve Öztürk', 'Konya', 'Türkiye', 'Bireysel'),
(55, 'Emine Yılmaz', 'Ankara', 'Türkiye', 'Bireysel'),
(56, 'Burak Yıldız', 'Ankara', 'Türkiye', 'Bireysel'),
(57, 'Fatma Arslan', 'Gaziantep', 'Türkiye', 'Bireysel'),
(58, 'Ayşe Çelik', 'Gaziantep', 'Türkiye', 'Bireysel'),
(59, 'Ece Kaya', 'Gaziantep', 'Türkiye', 'Bireysel'),
(60, 'TR Holding A.Ş.', 'Ankara', 'Türkiye', 'Kurumsal'),
(61, 'Hasan Yılmaz', 'Ankara', 'Türkiye', 'Bireysel'),
(62, 'TR Lojistik A.Ş.', 'İzmir', 'Türkiye', 'Kurumsal'),
(63, 'Emine Şahin', 'Adana', 'Türkiye', 'Bireysel'),
(64, 'TR Lojistik A.Ş.', 'Adana', 'Türkiye', 'Kurumsal'),
(65, 'Zeynep Çelik', 'Gaziantep', 'Türkiye', 'Bireysel'),
(66, 'Burak Arslan', 'Gaziantep', 'Türkiye', 'Bireysel'),
(67, 'Mustafa Şahin', 'İstanbul', 'Türkiye', 'Bireysel'),
(68, 'Hasan Yılmaz 68', 'Konya', 'Türkiye', 'Bireysel'),
(69, 'Hüseyin Aydın', 'İzmir', 'Türkiye', 'Bireysel'),
(70, 'Hasan Kaya', 'İzmir', 'Türkiye', 'Bireysel'),
(71, 'Mehmet Şahin', 'Adana', 'Türkiye', 'Bireysel'),
(72, 'Ece Doğan', 'Bursa', 'Türkiye', 'Bireysel'),
(73, 'Ahmet Doğan', 'Ankara', 'Türkiye', 'Bireysel'),
(74, 'Hüseyin Doğan', 'Konya', 'Türkiye', 'Bireysel'),
(75, 'TR Lojistik A.Ş.', 'Konya', 'Türkiye', 'Kurumsal'),
(76, 'Zeynep Demir', 'Antalya', 'Türkiye', 'Bireysel'),
(77, 'Ece Kaya', 'İstanbul', 'Türkiye', 'Bireysel'),
(78, 'Hüseyin Kaya', 'Ankara', 'Türkiye', 'Bireysel'),
(79, 'Hasan Çelik', 'İzmir', 'Türkiye', 'Bireysel'),
(80, 'TR Teknoloji A.Ş.', 'Bursa', 'Türkiye', 'Kurumsal'),
(81, 'Ayşe Aydın', 'Antalya', 'Türkiye', 'Bireysel'),
(82, 'Elif Arslan', 'İstanbul', 'Türkiye', 'Bireysel'),
(83, 'TR Holding A.Ş.', 'Antalya', 'Türkiye', 'Kurumsal'),
(84, 'TR Teknoloji A.Ş.', 'İzmir', 'Türkiye', 'Kurumsal'),
(85, 'Ece Kaya', 'İzmir', 'Türkiye', 'Bireysel'),
(86, 'Hüseyin Şahin', 'Konya', 'Türkiye', 'Bireysel'),
(87, 'Merve Çelik', 'Gaziantep', 'Türkiye', 'Bireysel'),
(88, 'Ece Yılmaz', 'Ankara', 'Türkiye', 'Bireysel'),
(89, 'Can Çelik', 'İstanbul', 'Türkiye', 'Bireysel'),
(90, 'Elif Demir', 'Antalya', 'Türkiye', 'Bireysel'),
(91, 'Emine Arslan', 'Adana', 'Türkiye', 'Bireysel'),
(92, 'Mehmet Kaya', 'İzmir', 'Türkiye', 'Bireysel'),
(93, 'Can Yıldız', 'İzmir', 'Türkiye', 'Bireysel'),
(94, 'Ahmet Çelik', 'Konya', 'Türkiye', 'Bireysel'),
(95, 'TR Teknoloji A.Ş.', 'Konya', 'Türkiye', 'Kurumsal'),
(96, 'Fatma Kaya', 'Konya', 'Türkiye', 'Bireysel'),
(97, 'TR Yazılım A.Ş.', 'İzmir', 'Türkiye', 'Kurumsal'),
(98, 'TR Lojistik A.Ş.', 'İzmir', 'Türkiye', 'Kurumsal'),
(99, 'TR Lojistik A.Ş.', 'Adana', 'Türkiye', 'Kurumsal'),
(100, 'Burak Yıldız', 'Adana', 'Türkiye', 'Bireysel'),
(101, 'TR Lojistik A.Ş.', 'Antalya', 'Türkiye', 'Kurumsal'),
(102, 'Burak Kaya', 'Adana', 'Türkiye', 'Bireysel'),
(103, 'TR Yazılım A.Ş.', 'Bursa', 'Türkiye', 'Kurumsal'),
(104, 'Ece Aydın', 'Konya', 'Türkiye', 'Bireysel'),
(105, 'Elif Şahin', 'Bursa', 'Türkiye', 'Bireysel'),
(106, 'Fatma Öztürk', 'Konya', 'Türkiye', 'Bireysel'),
(107, 'Mehmet Çelik', 'Konya', 'Türkiye', 'Bireysel'),
(108, 'Zeynep Arslan', 'Konya', 'Türkiye', 'Bireysel'),
(109, 'TR Teknoloji A.Ş.', 'Antalya', 'Türkiye', 'Kurumsal'),
(110, 'Mustafa Yılmaz', 'Ankara', 'Türkiye', 'Bireysel'),
(111, 'Ali Yıldız', 'Adana', 'Türkiye', 'Bireysel'),
(112, 'Hasan Kaya', 'Adana', 'Türkiye', 'Bireysel'),
(113, 'TR Lojistik A.Ş.', 'Antalya', 'Türkiye', 'Kurumsal'),
(114, 'Zeynep Yılmaz', 'Bursa', 'Türkiye', 'Bireysel'),
(115, 'Mehmet Yıldız', 'Konya', 'Türkiye', 'Bireysel'),
(116, 'TR Teknoloji A.Ş.', 'Antalya', 'Türkiye', 'Kurumsal'),
(117, 'Merve Öztürk', 'Konya', 'Türkiye', 'Bireysel'),
(118, 'Mustafa Arslan', 'İzmir', 'Türkiye', 'Bireysel'),
(119, 'Merve Öztürk', 'İzmir', 'Türkiye', 'Bireysel'),
(120, 'Mustafa Öztürk', 'İstanbul', 'Türkiye', 'Bireysel'),
(121, 'Fatma Öztürk', 'Konya', 'Türkiye', 'Bireysel'),
(122, 'Emine Şahin', 'Gaziantep', 'Türkiye', 'Bireysel'),
(123, 'TR Lojistik A.Ş.', 'Ankara', 'Türkiye', 'Kurumsal'),
(124, 'Merve Doğan', 'Konya', 'Türkiye', 'Bireysel'),
(125, 'Elif Şahin', 'Antalya', 'Türkiye', 'Bireysel'),
(126, 'Fatma Demir', 'İstanbul', 'Türkiye', 'Bireysel'),
(127, 'Emine Doğan', 'Ankara', 'Türkiye', 'Bireysel'),
(128, 'Ece Doğan', 'Bursa', 'Türkiye', 'Bireysel'),
(129, 'TR Yazılım A.Ş.', 'Gaziantep', 'Türkiye', 'Kurumsal'),
(130, 'Ayşe Yılmaz', 'Ankara', 'Türkiye', 'Bireysel'),
(131, 'TR Lojistik A.Ş.', 'İzmir', 'Türkiye', 'Kurumsal'),
(132, 'TR Holding A.Ş.', 'Gaziantep', 'Türkiye', 'Kurumsal'),
(133, 'Fatma Kaya', 'Gaziantep', 'Türkiye', 'Bireysel'),
(134, 'Emine Arslan', 'Konya', 'Türkiye', 'Bireysel'),
(135, 'TR Yazılım A.Ş.', 'Adana', 'Türkiye', 'Kurumsal'),
(136, 'TR Holding A.Ş.', 'Gaziantep', 'Türkiye', 'Kurumsal'),
(137, 'TR Yazılım A.Ş.', 'Gaziantep', 'Türkiye', 'Kurumsal'),
(138, 'Fatma Çelik', 'Gaziantep', 'Türkiye', 'Bireysel'),
(139, 'Mustafa Aydın', 'Ankara', 'Türkiye', 'Bireysel'),
(140, 'TR Lojistik A.Ş.', 'Antalya', 'Türkiye', 'Kurumsal'),
(141, 'Ece Arslan', 'Ankara', 'Türkiye', 'Bireysel'),
(142, 'Fatma Öztürk', 'İzmir', 'Türkiye', 'Bireysel'),
(143, 'TR Teknoloji A.Ş.', 'Adana', 'Türkiye', 'Kurumsal'),
(144, 'Hasan Aydın', 'Adana', 'Türkiye', 'Bireysel'),
(145, 'Can Öztürk', 'Adana', 'Türkiye', 'Bireysel'),
(146, 'TR Holding A.Ş.', 'İstanbul', 'Türkiye', 'Kurumsal'),
(147, 'TR Holding A.Ş.', 'Adana', 'Türkiye', 'Kurumsal'),
(148, 'Ali Çelik', 'Adana', 'Türkiye', 'Bireysel'),
(149, 'TR Yazılım A.Ş.', 'Bursa', 'Türkiye', 'Kurumsal'),
(150, 'Mustafa Öztürk', 'Gaziantep', 'Türkiye', 'Bireysel'),
(151, 'Ali Öztürk', 'İzmir', 'Türkiye', 'Bireysel'),
(152, 'TR Lojistik A.Ş.', 'İstanbul', 'Türkiye', 'Kurumsal'),
(153, 'TR Holding A.Ş.', 'İstanbul', 'Türkiye', 'Kurumsal'),
(154, 'Zeynep Demir', 'Gaziantep', 'Türkiye', 'Bireysel'),
(155, 'Mustafa Öztürk', 'Konya', 'Türkiye', 'Bireysel'),
(156, 'Ali Yıldız', 'Adana', 'Türkiye', 'Bireysel'),
(157, 'Can Öztürk', 'Antalya', 'Türkiye', 'Bireysel'),
(158, 'TR Yazılım A.Ş.', 'İstanbul', 'Türkiye', 'Kurumsal'),
(159, 'TR Teknoloji A.Ş.', 'Konya', 'Türkiye', 'Kurumsal'),
(160, 'Mehmet Yılmaz', 'İstanbul', 'Türkiye', 'Bireysel'),
(161, 'TR Lojistik A.Ş.', 'İstanbul', 'Türkiye', 'Kurumsal'),
(162, 'Fatma Demir', 'Gaziantep', 'Türkiye', 'Bireysel'),
(163, 'TR Holding A.Ş.', 'Bursa', 'Türkiye', 'Kurumsal'),
(164, 'Mustafa Yıldız', 'İzmir', 'Türkiye', 'Bireysel'),
(165, 'Burak Kaya', 'İzmir', 'Türkiye', 'Bireysel'),
(166, 'TR Teknoloji A.Ş.', 'İstanbul', 'Türkiye', 'Kurumsal'),
(167, 'TR Holding A.Ş.', 'Adana', 'Türkiye', 'Kurumsal'),
(168, 'Burak Şahin', 'Ankara', 'Türkiye', 'Bireysel'),
(169, 'Can Şahin', 'Ankara', 'Türkiye', 'Bireysel'),
(170, 'TR Ticaret A.Ş.', 'Ankara', 'Türkiye', 'Kurumsal'),
(171, 'TR Holding A.Ş.', 'İstanbul', 'Türkiye', 'Kurumsal'),
(172, 'Zeynep Yıldız', 'Ankara', 'Türkiye', 'Bireysel'),
(173, 'Ali Yılmaz', 'Adana', 'Türkiye', 'Bireysel'),
(174, 'TR Teknoloji A.Ş.', 'Adana', 'Türkiye', 'Kurumsal'),
(175, 'TR Yazılım A.Ş.', 'İzmir', 'Türkiye', 'Kurumsal'),
(176, 'Burak Arslan', 'Antalya', 'Türkiye', 'Bireysel'),
(177, 'Ece Arslan', 'Gaziantep', 'Türkiye', 'Bireysel'),
(178, 'Can Doğan', 'Antalya', 'Türkiye', 'Bireysel'),
(179, 'Fatma Kaya', 'Antalya', 'Türkiye', 'Bireysel'),
(180, 'TR Lojistik A.Ş.', 'Gaziantep', 'Türkiye', 'Kurumsal'),
(181, 'Merve Öztürk', 'Konya', 'Türkiye', 'Bireysel'),
(182, 'Can Yıldız', 'İzmir', 'Türkiye', 'Bireysel'),
(183, 'Ali Çelik', 'Konya', 'Türkiye', 'Bireysel'),
(184, 'Hüseyin Çelik', 'İstanbul', 'Türkiye', 'Bireysel'),
(185, 'Fatma Kaya', 'Bursa', 'Türkiye', 'Bireysel'),
(186, 'TR Yazılım A.Ş.', 'Bursa', 'Türkiye', 'Kurumsal'),
(187, 'TR Yazılım A.Ş.', 'Gaziantep', 'Türkiye', 'Kurumsal'),
(188, 'TR Teknoloji A.Ş.', 'Antalya', 'Türkiye', 'Kurumsal'),
(189, 'Burak Şahin', 'Antalya', 'Türkiye', 'Bireysel'),
(190, 'TR Ticaret A.Ş.', 'Gaziantep', 'Türkiye', 'Kurumsal'),
(191, 'Ali Öztürk', 'Konya', 'Türkiye', 'Bireysel'),
(192, 'Emine Çelik', 'Antalya', 'Türkiye', 'Bireysel'),
(193, 'Mehmet Şahin', 'Konya', 'Türkiye', 'Bireysel'),
(194, 'Hasan Demir', 'Bursa', 'Türkiye', 'Bireysel'),
(195, 'Emine Çelik', 'Antalya', 'Türkiye', 'Bireysel'),
(196, 'TR Lojistik A.Ş.', 'Antalya', 'Türkiye', 'Kurumsal'),
(197, 'Ayşe Çelik', 'İstanbul', 'Türkiye', 'Bireysel'),
(198, 'TR Lojistik A.Ş.', 'Antalya', 'Türkiye', 'Kurumsal'),
(199, 'Ahmet Arslan', 'Antalya', 'Türkiye', 'Bireysel'),
(200, 'TR Lojistik A.Ş.', 'Gaziantep', 'Türkiye', 'Kurumsal'),
(201, 'Hans Weber', 'Köln', 'Almanya', 'Bireysel'),
(202, 'Lena Schneider', 'Berlin', 'Almanya', 'Bireysel'),
(203, 'Sophie Schmidt', 'Düsseldorf', 'Almanya', 'Bireysel'),
(204, 'Sophie Schmidt', 'Frankfurt', 'Almanya', 'Bireysel'),
(205, 'Hans Schneider', 'Hamburg', 'Almanya', 'Bireysel'),
(206, 'DE Handel GmbH', 'Berlin', 'Almanya', 'Kurumsal'),
(207, 'DE Tech GmbH', 'Frankfurt', 'Almanya', 'Kurumsal'),
(208, 'DE Industrie GmbH', 'Frankfurt', 'Almanya', 'Kurumsal'),
(209, 'DE Logistik GmbH', 'Düsseldorf', 'Almanya', 'Kurumsal'),
(210, 'Sophie Becker', 'Münih', 'Almanya', 'Bireysel'),
(211, 'DE Software GmbH', 'Münih', 'Almanya', 'Kurumsal'),
(212, 'Hans Schmidt', 'Düsseldorf', 'Almanya', 'Bireysel'),
(213, 'Julia Weber', 'Stuttgart', 'Almanya', 'Bireysel'),
(214, 'Julia Schneider', 'Frankfurt', 'Almanya', 'Bireysel'),
(215, 'Hans Wagner', 'Köln', 'Almanya', 'Bireysel'),
(216, 'DE Software GmbH', 'Münih', 'Almanya', 'Kurumsal'),
(217, 'Thomas Weber', 'Stuttgart', 'Almanya', 'Bireysel'),
(218, 'DE Tech GmbH', 'Stuttgart', 'Almanya', 'Kurumsal'),
(219, 'Thomas Fischer', 'Köln', 'Almanya', 'Bireysel'),
(220, 'Julia Schneider', 'Münih', 'Almanya', 'Bireysel'),
(221, 'DE Tech GmbH', 'Berlin', 'Almanya', 'Kurumsal'),
(222, 'Thomas Weber', 'Köln', 'Almanya', 'Bireysel'),
(223, 'Thomas Wagner', 'Münih', 'Almanya', 'Bireysel'),
(224, 'Sophie Becker', 'Berlin', 'Almanya', 'Bireysel'),
(225, 'Max Meyer', 'Frankfurt', 'Almanya', 'Bireysel'),
(226, 'Peter Fischer', 'Stuttgart', 'Almanya', 'Bireysel'),
(227, 'DE Industrie GmbH', 'Frankfurt', 'Almanya', 'Kurumsal'),
(228, 'DE Handel GmbH', 'Frankfurt', 'Almanya', 'Kurumsal'),
(229, 'Anna Becker', 'Frankfurt', 'Almanya', 'Bireysel'),
(230, 'DE Handel GmbH', 'Hamburg', 'Almanya', 'Kurumsal'),
(231, 'DE Software GmbH', 'Stuttgart', 'Almanya', 'Kurumsal'),
(232, 'DE Tech GmbH', 'Köln', 'Almanya', 'Kurumsal'),
(233, 'Lena Meyer', 'Stuttgart', 'Almanya', 'Bireysel'),
(234, 'Anna Meyer', 'Köln', 'Almanya', 'Bireysel'),
(235, 'DE Handel GmbH', 'Stuttgart', 'Almanya', 'Kurumsal'),
(236, 'DE Industrie GmbH', 'Berlin', 'Almanya', 'Kurumsal'),
(237, 'Lena Weber', 'Münih', 'Almanya', 'Bireysel'),
(238, 'Max Müller', 'Stuttgart', 'Almanya', 'Bireysel'),
(239, 'DE Software GmbH', 'Köln', 'Almanya', 'Kurumsal'),
(240, 'Lukas Meyer', 'Frankfurt', 'Almanya', 'Bireysel'),
(241, 'DE Software GmbH', 'Düsseldorf', 'Almanya', 'Kurumsal'),
(242, 'Thomas Schneider', 'Münih', 'Almanya', 'Bireysel'),
(243, 'Sophie Schmidt', 'Berlin', 'Almanya', 'Bireysel'),
(244, 'DE Industrie GmbH', 'Düsseldorf', 'Almanya', 'Kurumsal'),
(245, 'Anna Weber', 'Frankfurt', 'Almanya', 'Bireysel'),
(246, 'Max Schmidt', 'Hamburg', 'Almanya', 'Bireysel'),
(247, 'DE Tech GmbH', 'Köln', 'Almanya', 'Kurumsal'),
(248, 'DE Logistik GmbH', 'Köln', 'Almanya', 'Kurumsal'),
(249, 'DE Handel GmbH', 'Frankfurt', 'Almanya', 'Kurumsal'),
(250, 'DE Software GmbH', 'Düsseldorf', 'Almanya', 'Kurumsal'),
(251, 'Sophie Fischer', 'Köln', 'Almanya', 'Bireysel'),
(252, 'Max Fischer', 'Frankfurt', 'Almanya', 'Bireysel'),
(253, 'Anna Schmidt', 'Münih', 'Almanya', 'Bireysel'),
(254, 'DE Software GmbH', 'Münih', 'Almanya', 'Kurumsal'),
(255, 'DE Industrie GmbH', 'Münih', 'Almanya', 'Kurumsal'),
(256, 'DE Handel GmbH', 'Stuttgart', 'Almanya', 'Kurumsal'),
(257, 'Marie Becker', 'Düsseldorf', 'Almanya', 'Bireysel'),
(258, 'Lukas Becker', 'Münih', 'Almanya', 'Bireysel'),
(259, 'Lukas Wagner', 'Köln', 'Almanya', 'Bireysel'),
(260, 'DE Logistik GmbH', 'Stuttgart', 'Almanya', 'Kurumsal'),
(261, 'Max Fischer', 'Düsseldorf', 'Almanya', 'Bireysel'),
(262, 'DE Tech GmbH', 'Münih', 'Almanya', 'Kurumsal'),
(263, 'DE Software GmbH', 'Köln', 'Almanya', 'Kurumsal'),
(264, 'DE Logistik GmbH', 'Köln', 'Almanya', 'Kurumsal'),
(265, 'DE Logistik GmbH', 'Frankfurt', 'Almanya', 'Kurumsal'),
(266, 'DE Handel GmbH', 'Düsseldorf', 'Almanya', 'Kurumsal'),
(267, 'Sophie Schmidt', 'Frankfurt', 'Almanya', 'Bireysel'),
(268, 'DE Tech GmbH', 'Stuttgart', 'Almanya', 'Kurumsal'),
(269, 'Anna Schmidt', 'Köln', 'Almanya', 'Bireysel'),
(270, 'DE Handel GmbH', 'Münih', 'Almanya', 'Kurumsal'),
(271, 'Max Schmidt', 'Düsseldorf', 'Almanya', 'Bireysel'),
(272, 'Lukas Wagner', 'Münih', 'Almanya', 'Bireysel'),
(273, 'Sophie Müller', 'Frankfurt', 'Almanya', 'Bireysel'),
(274, 'Thomas Fischer', 'Stuttgart', 'Almanya', 'Bireysel'),
(275, 'Peter Schmidt', 'Köln', 'Almanya', 'Bireysel'),
(276, 'Thomas Müller', 'Berlin', 'Almanya', 'Bireysel'),
(277, 'Hans Weber', 'Münih', 'Almanya', 'Bireysel'),
(278, 'Anna Fischer', 'Frankfurt', 'Almanya', 'Bireysel'),
(279, 'Anna Schneider', 'Hamburg', 'Almanya', 'Bireysel'),
(280, 'Max Fischer', 'Köln', 'Almanya', 'Bireysel'),
(281, 'DE Logistik GmbH', 'Hamburg', 'Almanya', 'Kurumsal'),
(282, 'Thomas Becker', 'Münih', 'Almanya', 'Bireysel'),
(283, 'DE Software GmbH', 'Münih', 'Almanya', 'Kurumsal'),
(284, 'DE Logistik GmbH', 'Berlin', 'Almanya', 'Kurumsal'),
(285, 'Lena Weber', 'Stuttgart', 'Almanya', 'Bireysel'),
(286, 'DE Handel GmbH', 'Köln', 'Almanya', 'Kurumsal'),
(287, 'DE Logistik GmbH', 'Köln', 'Almanya', 'Kurumsal'),
(288, 'DE Tech GmbH', 'Hamburg', 'Almanya', 'Kurumsal'),
(289, 'Lena Weber', 'Stuttgart', 'Almanya', 'Bireysel'),
(290, 'Max Weber', 'Berlin', 'Almanya', 'Bireysel'),
(291, 'Hans Becker', 'Düsseldorf', 'Almanya', 'Bireysel'),
(292, 'DE Handel GmbH', 'Düsseldorf', 'Almanya', 'Kurumsal'),
(293, 'DE Industrie GmbH', 'Düsseldorf', 'Almanya', 'Kurumsal'),
(294, 'Julia Weber', 'Stuttgart', 'Almanya', 'Bireysel'),
(295, 'DE Logistik GmbH', 'Stuttgart', 'Almanya', 'Kurumsal'),
(296, 'Hans Weber', 'Düsseldorf', 'Almanya', 'Bireysel'),
(297, 'Marie Meyer', 'Stuttgart', 'Almanya', 'Bireysel'),
(298, 'Thomas Meyer', 'Stuttgart', 'Almanya', 'Bireysel'),
(299, 'Julia Schneider', 'Düsseldorf', 'Almanya', 'Bireysel'),
(300, 'Lena Weber', 'Düsseldorf', 'Almanya', 'Bireysel'),
(301, 'Sophie Weber', 'Stuttgart', 'Almanya', 'Bireysel'),
(302, 'DE Tech GmbH', 'Köln', 'Almanya', 'Kurumsal'),
(303, 'DE Logistik GmbH', 'Düsseldorf', 'Almanya', 'Kurumsal'),
(304, 'DE Software GmbH', 'Düsseldorf', 'Almanya', 'Kurumsal'),
(305, 'DE Handel GmbH', 'Berlin', 'Almanya', 'Kurumsal'),
(306, 'DE Tech GmbH', 'Münih', 'Almanya', 'Kurumsal'),
(307, 'Sophie Meyer', 'Stuttgart', 'Almanya', 'Bireysel'),
(308, 'DE Handel GmbH', 'Frankfurt', 'Almanya', 'Kurumsal'),
(309, 'Lena Schmidt', 'Stuttgart', 'Almanya', 'Bireysel'),
(310, 'Hans Meyer', 'Frankfurt', 'Almanya', 'Bireysel'),
(311, 'Peter Becker', 'Stuttgart', 'Almanya', 'Bireysel'),
(312, 'Max Schmidt', 'Hamburg', 'Almanya', 'Bireysel'),
(313, 'Hans Weber', 'Köln', 'Almanya', 'Bireysel'),
(314, 'Julia Schneider', 'Köln', 'Almanya', 'Bireysel'),
(315, 'Lukas Wagner', 'Frankfurt', 'Almanya', 'Bireysel'),
(316, 'DE Logistik GmbH', 'Köln', 'Almanya', 'Kurumsal'),
(317, 'DE Software GmbH', 'Frankfurt', 'Almanya', 'Kurumsal'),
(318, 'Thomas Müller', 'Stuttgart', 'Almanya', 'Bireysel'),
(319, 'Sophie Becker', 'Hamburg', 'Almanya', 'Bireysel'),
(320, 'DE Tech GmbH', 'Stuttgart', 'Almanya', 'Kurumsal'),
(321, 'Lena Müller', 'Köln', 'Almanya', 'Bireysel'),
(322, 'Peter Becker', 'Berlin', 'Almanya', 'Bireysel'),
(323, 'DE Industrie GmbH', 'Berlin', 'Almanya', 'Kurumsal'),
(324, 'Lena Fischer', 'Hamburg', 'Almanya', 'Bireysel'),
(325, 'DE Logistik GmbH', 'Berlin', 'Almanya', 'Kurumsal'),
(326, 'DE Industrie GmbH', 'Hamburg', 'Almanya', 'Kurumsal'),
(327, 'Julia Meyer', 'Düsseldorf', 'Almanya', 'Bireysel'),
(328, 'Marie Müller', 'Münih', 'Almanya', 'Bireysel'),
(329, 'DE Logistik GmbH', 'Hamburg', 'Almanya', 'Kurumsal'),
(330, 'Anna Schmidt', 'Stuttgart', 'Almanya', 'Bireysel'),
(331, 'DE Logistik GmbH', 'Berlin', 'Almanya', 'Kurumsal'),
(332, 'Julia Meyer', 'Berlin', 'Almanya', 'Bireysel'),
(333, 'Hans Schneider', 'Stuttgart', 'Almanya', 'Bireysel'),
(334, 'Peter Schmidt', 'Köln', 'Almanya', 'Bireysel'),
(335, 'Lena Schmidt', 'Köln', 'Almanya', 'Bireysel'),
(336, 'Marie Müller', 'Stuttgart', 'Almanya', 'Bireysel'),
(337, 'DE Industrie GmbH', 'Münih', 'Almanya', 'Kurumsal'),
(338, 'Hans Müller', 'Köln', 'Almanya', 'Bireysel'),
(339, 'DE Software GmbH', 'Stuttgart', 'Almanya', 'Kurumsal'),
(340, 'Sophie Schmidt', 'Berlin', 'Almanya', 'Bireysel'),
(341, 'Anna Schmidt', 'Hamburg', 'Almanya', 'Bireysel'),
(342, 'Marie Meyer', 'Köln', 'Almanya', 'Bireysel'),
(343, 'DE Industrie GmbH', 'Münih', 'Almanya', 'Kurumsal'),
(344, 'Marie Wagner', 'Berlin', 'Almanya', 'Bireysel'),
(345, 'DE Tech GmbH', 'Düsseldorf', 'Almanya', 'Kurumsal'),
(346, 'DE Industrie GmbH', 'Stuttgart', 'Almanya', 'Kurumsal'),
(347, 'DE Software GmbH', 'Köln', 'Almanya', 'Kurumsal'),
(348, 'DE Software GmbH', 'Münih', 'Almanya', 'Kurumsal'),
(349, 'DE Software GmbH', 'Köln', 'Almanya', 'Kurumsal'),
(350, 'DE Handel GmbH', 'Köln', 'Almanya', 'Kurumsal'),
(351, 'David Miller', 'Los Angeles', 'Amerika', 'Bireysel'),
(352, 'US Solutions Inc', 'New York', 'Amerika', 'Kurumsal'),
(353, 'Emily Johnson', 'Houston', 'Amerika', 'Bireysel'),
(354, 'Jessica Williams', 'Phoenix', 'Amerika', 'Bireysel'),
(355, 'Daniel Miller', 'Dallas', 'Amerika', 'Bireysel'),
(356, 'Jessica Davis', 'Miami', 'Amerika', 'Bireysel'),
(357, 'US Tech Inc', 'Chicago', 'Amerika', 'Kurumsal'),
(358, 'Jessica Johnson', 'Phoenix', 'Amerika', 'Bireysel'),
(359, 'Michael Wilson', 'Los Angeles', 'Amerika', 'Bireysel'),
(360, 'US Logistics Inc', 'Miami', 'Amerika', 'Kurumsal'),
(361, 'Emily Jones', 'Phoenix', 'Amerika', 'Bireysel'),
(362, 'James Smith', 'Phoenix', 'Amerika', 'Bireysel'),
(363, 'US Logistics Inc', 'New York', 'Amerika', 'Kurumsal'),
(364, 'David Miller', 'Chicago', 'Amerika', 'Bireysel'),
(365, 'Michael Davis', 'New York', 'Amerika', 'Bireysel'),
(366, 'John Johnson', 'Dallas', 'Amerika', 'Bireysel'),
(367, 'James Davis', 'Houston', 'Amerika', 'Bireysel'),
(368, 'Jessica Jones', 'Dallas', 'Amerika', 'Bireysel'),
(369, 'Olivia Johnson', 'New York', 'Amerika', 'Bireysel'),
(370, 'Olivia Smith', 'Dallas', 'Amerika', 'Bireysel'),
(371, 'Ashley Davis', 'Houston', 'Amerika', 'Bireysel'),
(372, 'James Jones','Los Angeles', 'Amerika', 'Bireysel'),
(373, 'US Tech Inc', 'Chicago', 'Amerika', 'Kurumsal'),
(374, 'David Wilson', 'Phoenix', 'Amerika', 'Bireysel'),
(375, 'US Tech Inc', 'Los Angeles', 'Amerika', 'Kurumsal'),
(376, 'Olivia Smith', 'New York', 'Amerika', 'Bireysel'),
(377, 'Sarah Williams', 'Miami', 'Amerika', 'Bireysel'),
(378, 'Jessica Johnson', 'New York', 'Amerika', 'Bireysel'),
(379, 'James Williams', 'Los Angeles', 'Amerika', 'Bireysel'),
(380, 'Sarah Miller', 'New York', 'Amerika', 'Bireysel'),
(381, 'John Davis', 'New York', 'Amerika', 'Bireysel'),
(382, 'Emily Miller', 'Phoenix', 'Amerika', 'Bireysel'),
(383, 'James Davis', 'Chicago', 'Amerika', 'Bireysel'),
(384, 'John Miller', 'Los Angeles', 'Amerika', 'Bireysel'),
(385, 'US Industries Inc', 'Houston', 'Amerika', 'Kurumsal'),
(386, 'US Logistics Inc', 'New York', 'Amerika', 'Kurumsal'),
(387, 'Emily Brown', 'Houston', 'Amerika', 'Bireysel'),
(388, 'Daniel Johnson', 'Houston', 'Amerika', 'Bireysel'),
(389, 'US Logistics Inc', 'Los Angeles', 'Amerika', 'Kurumsal'),
(390, 'Michael Johnson', 'Phoenix', 'Amerika', 'Bireysel'),
(391, 'Daniel Brown', 'Miami', 'Amerika', 'Bireysel'),
(392, 'Michael Brown', 'New York', 'Amerika', 'Bireysel'),
(393, 'Sarah Williams', 'Phoenix', 'Amerika', 'Bireysel'),
(394, 'Emily Williams', 'Miami', 'Amerika', 'Bireysel'),
(395, 'Ashley Wilson', 'Dallas', 'Amerika', 'Bireysel'),
(396, 'US Industries Inc', 'Dallas', 'Amerika', 'Kurumsal'),
(397, 'Olivia Miller', 'Miami', 'Amerika', 'Bireysel'),
(398, 'US Logistics Inc', 'Los Angeles', 'Amerika', 'Kurumsal'),
(399, 'Ashley Wilson', 'Dallas', 'Amerika', 'Bireysel'),
(400, 'David Smith', 'Chicago', 'Amerika', 'Bireysel'),
(401, 'David Wilson', 'Houston', 'Amerika', 'Bireysel'),
(402, 'Jessica Jones', 'New York', 'Amerika', 'Bireysel'),
(403, 'Emily Davis', 'Houston', 'Amerika', 'Bireysel'),
(404, 'John Wilson', 'Miami', 'Amerika', 'Bireysel'),
(405, 'Sarah Miller', 'Phoenix', 'Amerika', 'Bireysel'),
(406, 'Michael Smith', 'Houston', 'Amerika', 'Bireysel'),
(407, 'Jessica Johnson', 'Phoenix', 'Amerika', 'Bireysel'),
(408, 'John Brown', 'Dallas', 'Amerika', 'Bireysel'),
(409, 'Ashley Williams', 'Chicago', 'Amerika', 'Bireysel'),
(410, 'David Davis', 'Houston', 'Amerika', 'Bireysel'),
(411, 'US Industries Inc', 'New York', 'Amerika', 'Kurumsal'),
(412, 'US Logistics Inc', 'New York', 'Amerika', 'Kurumsal'),
(413, 'Daniel Davis', 'Chicago', 'Amerika', 'Bireysel'),
(414, 'Olivia Williams', 'Chicago', 'Amerika', 'Bireysel'),
(415, 'Michael Miller', 'Chicago', 'Amerika', 'Bireysel'),
(416, 'US Solutions Inc', 'Los Angeles', 'Amerika', 'Kurumsal'),
(417, 'Emily Jones', 'Phoenix', 'Amerika', 'Bireysel'),
(418, 'Jessica Williams', 'Dallas', 'Amerika', 'Bireysel'),
(419, 'US Industries Inc', 'New York', 'Amerika', 'Kurumsal'),
(420, 'James Miller', 'New York', 'Amerika', 'Bireysel'),
(421, 'Michael Brown', 'Chicago', 'Amerika', 'Bireysel'),
(422, 'US Solutions Inc', 'Los Angeles', 'Amerika', 'Kurumsal'),
(423, 'Michael Williams', 'New York', 'Amerika', 'Bireysel'),
(424, 'Emily Smith', 'Dallas', 'Amerika', 'Bireysel'),
(425, 'Olivia Williams', 'Phoenix', 'Amerika', 'Bireysel'),
(426, 'Michael Williams', 'Miami', 'Amerika', 'Bireysel'),
(427, 'US Industries Inc', 'Miami', 'Amerika', 'Kurumsal'),
(428, 'US Solutions Inc', 'New York', 'Amerika', 'Kurumsal'),
(429, 'Sarah Wilson', 'Phoenix', 'Amerika', 'Bireysel'),
(430, 'Ashley Brown', 'Phoenix', 'Amerika', 'Bireysel'),
(431, 'Ashley Brown', 'Chicago', 'Amerika', 'Bireysel'),
(432, 'US Industries Inc', 'Houston', 'Amerika', 'Kurumsal'),
(433, 'David Davis', 'Phoenix', 'Amerika', 'Bireysel'),
(434, 'Michael Brown', 'Miami', 'Amerika', 'Bireysel'),
(435, 'David Smith', 'Dallas', 'Amerika', 'Bireysel'),
(436, 'Jessica Johnson', 'Dallas', 'Amerika', 'Bireysel'),
(437, 'US Tech Inc', 'Chicago', 'Amerika', 'Kurumsal'),
(438, 'Michael Jones', 'Houston', 'Amerika', 'Bireysel'),
(439, 'US Retail Inc', 'Miami', 'Amerika', 'Kurumsal'),
(440, 'Sarah Wilson', 'Chicago', 'Amerika', 'Bireysel'),
(441, 'US Solutions Inc', 'New York', 'Amerika', 'Kurumsal'),
(442, 'Jessica Brown', 'Houston', 'Amerika', 'Bireysel'),
(443, 'US Logistics Inc', 'Los Angeles', 'Amerika', 'Kurumsal'),
(444, 'Emily Miller', 'Miami', 'Amerika', 'Bireysel'),
(445, 'John Jones', 'Miami', 'Amerika', 'Bireysel'),
(446, 'Michael Wilson', 'Houston', 'Amerika', 'Bireysel'),
(447, 'Emily Smith', 'Chicago', 'Amerika', 'Bireysel'),
(448, 'Michael Davis', 'New York', 'Amerika', 'Bireysel'),
(449, 'US Retail Inc', 'Chicago', 'Amerika', 'Kurumsal'),
(450, 'Sarah Davis', 'Dallas', 'Amerika', 'Bireysel'),
(451, 'US Solutions Inc', 'New York', 'Amerika', 'Kurumsal'),
(452, 'Ashley Smith', 'Dallas', 'Amerika', 'Bireysel'),
(453, 'Sarah Williams', 'Chicago', 'Amerika', 'Bireysel'),
(454, 'Olivia Miller', 'Los Angeles', 'Amerika', 'Bireysel'),
(455, 'Michael Johnson', 'Phoenix', 'Amerika', 'Bireysel'),
(456, 'US Tech Inc', 'Phoenix', 'Amerika', 'Kurumsal'),
(457, 'Daniel Smith', 'Houston', 'Amerika', 'Bireysel'),
(458, 'US Tech Inc', 'Dallas', 'Amerika', 'Kurumsal'),
(459, 'Jessica Jones', 'Dallas', 'Amerika', 'Bireysel'),
(460, 'Emily Miller', 'Los Angeles', 'Amerika', 'Bireysel'),
(461, 'US Tech Inc', 'Miami', 'Amerika', 'Kurumsal'),
(462, 'Jessica Williams', 'New York', 'Amerika', 'Bireysel'),
(463, 'Jessica Williams', 'Miami', 'Amerika', 'Bireysel'),
(464, 'US Solutions Inc', 'Dallas', 'Amerika', 'Kurumsal'),
(465, 'Michael Williams', 'New York', 'Amerika', 'Bireysel'),
(466, 'US Solutions Inc', 'New York', 'Amerika', 'Kurumsal'),
(467, 'John Brown', 'New York', 'Amerika', 'Bireysel'),
(468, 'David Davis', 'Miami', 'Amerika', 'Bireysel'),
(469, 'David Smith', 'Miami', 'Amerika', 'Bireysel'),
(470, 'David Miller', 'Miami', 'Amerika', 'Bireysel'),
(471, 'US Logistics Inc', 'Chicago', 'Amerika', 'Kurumsal'),
(472, 'Jessica Davis', 'Houston', 'Amerika', 'Bireysel'),
(473, 'US Solutions Inc', 'Chicago', 'Amerika', 'Kurumsal'),
(474, 'US Solutions Inc', 'Dallas', 'Amerika', 'Kurumsal'),
(475, 'Daniel Jones', 'Miami', 'Amerika', 'Bireysel'),
(476, 'James Johnson', 'Houston', 'Amerika', 'Bireysel'),
(477, 'Michael Jones', 'Chicago', 'Amerika', 'Bireysel'),
(478, 'Jessica Jones', 'Chicago', 'Amerika', 'Bireysel'),
(479, 'James Williams', 'Dallas', 'Amerika', 'Bireysel'),
(480, 'Ashley Smith', 'Dallas', 'Amerika', 'Bireysel'),
(481, 'US Logistics Inc', 'Phoenix', 'Amerika', 'Kurumsal'),
(482, 'US Logistics Inc', 'Dallas', 'Amerika', 'Kurumsal'),
(483, 'US Tech Inc', 'New York', 'Amerika', 'Kurumsal'),
(484, 'US Solutions Inc', 'Chicago', 'Amerika', 'Kurumsal'),
(485, 'Michael Smith', 'Los Angeles', 'Amerika', 'Bireysel'),
(486, 'US Solutions Inc', 'New York', 'Amerika', 'Kurumsal'),
(487, 'Sarah Miller', 'Chicago', 'Amerika', 'Bireysel'),
(488, 'Olivia Smith', 'Phoenix', 'Amerika', 'Bireysel'),
(489, 'Ashley Miller', 'Chicago', 'Amerika', 'Bireysel'),
(490, 'Emily Williams', 'Phoenix', 'Amerika', 'Bireysel'),
(491, 'Jessica Jones', 'Los Angeles', 'Amerika', 'Bireysel'),
(492, 'US Tech Inc', 'Dallas', 'Amerika', 'Kurumsal'),
(493, 'Daniel Davis', 'Phoenix', 'Amerika', 'Bireysel'),
(494, 'David Wilson', 'Los Angeles', 'Amerika', 'Bireysel'),
(495, 'US Logistics Inc', 'Dallas', 'Amerika', 'Kurumsal'),
(496, 'US Solutions Inc', 'Los Angeles', 'Amerika', 'Kurumsal'),
(497, 'Emily Wilson', 'Los Angeles', 'Amerika', 'Bireysel'),
(498, 'US Solutions Inc', 'New York', 'Amerika', 'Kurumsal'),
(499, 'US Logistics Inc', 'Dallas', 'Amerika', 'Kurumsal'),
(500, 'Emily Jones', 'Chicago', 'Amerika', 'Bireysel');